INSERT INTO RepliesByType (category, webhook_action, reply_text) VALUES
('Report Missed Recycling Collection', false, 'For missed recycling collection, contact: Central Virginia Waste Management Authority at 804-340-0900.'),
('Report Missed Trash Collection', false, 'To report missed trash, call 804-646-1798.'),
('How To Report A Gas Leak', false, 'All gas leaks are handled as emergencies. If you think you smell a natural gas leak, immediately call (804) 646-4646. If there is immediate danger, please call 911.'),
('Report Water Leak Or Missing Utility Cover', false, 'Water leaks and missing utility covers are handled as emergencies and should be reported immediately. To ensure response within 12 hours please call 804-646-4646 and press 1. This number is available 24 hours a day.'),
('How To Report On-Street Parking Violation', false, 'During weekdays, call (804) 649-3025. After hours or weekends, call the non-emergency police line at (804) 646-5100.'),
('On Street Parking Violations', false, 'During weekdays, call (804) 649-3025. After hours or weekends, call the non-emergency police line at (804) 646-5100.'),
('Contact Animal Care And Control', false, 'During weekdays, call (804) 646-5573. After hours or weekends, call the non-emergency police line at (804) 646-5100.'),
('How To Request Dead Animal Removal', false, 'During weekdays, call (804) 646-5573. After hours or weekends, call the non-emergency police line at (804) 646-5100.'),
('Downed Trees Or Other Obstacles Blocking Roads Or Rights Of Way', false, 'Call the non-emergency police line at (804) 646-5100 to report this issue.'),
('Traffic Signals That Have Been Knocked Downed Or Are Not Functioning', false, 'Call the non-emergency police line at (804) 646-5100 to report this issue.'),
('Report Stop Sign Or Traffic Signal Emergency', false, 'Call the non-emergency police line at (804) 646-5100 to report this issue.'),
('Storm Cleanup For Branches And Tree Debris', false, 'Call the non-emergency police line at (804) 646-5100 to report this issue.'),
('Request Collection of Storm Debris', false, 'Call the non-emergency police line at (804) 646-5100 to report this issue.'),
('How To Report Abandoned Vehicles On City Streets', false, 'Call the non-emergency police line at (804) 646-5100 to report this issue.'),
('Report Issue With Scooter', false, 'To report non-emergency issues related to scooters, use the toll-free number found on each scooter. (Scooters are not owned, managed or maintained directly by the City.) For accidents and emergencies, call 911.'),
('Pothole On Road', true, 'Thanks for reporting this pothole. We''ve filed this request with RVA311 on your behalf. Pothole requests are inspected and repaired within 14 days, weather permitting. If this is a duplicate request, if no pothole can be found, or extended paving is needed, timelines could be extended.'),
('Report Sinkhole', false, 'This request cannot yet be handled via text - go to RVA311.com or call 3-1-1 to submit your request.'),
('Repair Road', false, 'This request cannot yet be handled via text - go to RVA311.com or call 3-1-1 to submit your request.'),
('Repair Sidewalk Or Ramp', true, 'Thanks for reporting this. We''ve filed this with RVA311 on your behalf. The entire block of the reported location will be inspected to determine scope of work, and repairs may take up to 365 days. Teams will make every effort to add comments to share results of inspection - check them at RVA311.com.'),
('Repair Alley', false, 'This request cannot yet be handled via text - go to RVA311.com or call 3-1-1 to submit your request.'),
('Repair Curbs And Gutters', false, 'This request cannot yet be handled via text - go to RVA311.com or call 3-1-1 to submit your request.'),
('Pavement Markings', false, 'This request cannot yet be handled via text - go to RVA311.com or call 3-1-1 to submit your request.'),
('Report Neighborhood Roadway Safety Concern', false, 'This request cannot yet be handled via text - go to RVA311.com or call 3-1-1 to submit your request.'),
('Repair Bridge', false, 'This request cannot yet be handled via text - go to RVA311.com or call 3-1-1 to submit your request.'),
('Report Noisy Sewer Manhole Cover', false, 'This request cannot yet be handled via text - go to RVA311.com or call 3-1-1 to submit your request.'),
('Raise Or Lower Sewer Manhole', false, 'This request cannot yet be handled via text - go to RVA311.com or call 3-1-1 to submit your request.'),
('Handicap Parking Sign', false, 'This request cannot yet be handled via text - go to RVA311.com or call 3-1-1 to submit your request.'),
('Traffic And Street Signs', false, 'This request cannot yet be handled via text - go to RVA311.com or call 3-1-1 to submit your request.'),
('Repair Electronic Traffic Signal', false, 'This request cannot yet be handled via text - go to RVA311.com or call 3-1-1 to submit your request.'),
('Request New Streetlight', false, 'This request cannot yet be handled via text - go to RVA311.com or call 3-1-1 to submit your request.'),
('Repair Existing Streetlight', false, 'This request cannot yet be handled via text - go to RVA311.com or call 3-1-1 to submit your request.'),
('Request New Tree Planting', false, 'This request cannot yet be handled via text - go to RVA311.com or call 3-1-1 to submit your request.'),
('Assess Existing Tree Or Stump', false, 'This request cannot yet be handled via text - go to RVA311.com or call 3-1-1 to submit your request.'),
('Maintain Grass Or Vegetation In Public Right Of Way', false, 'This request cannot yet be handled via text - go to RVA311.com or call 3-1-1 to submit your request.'),
('Report Issue On Richmond Park Trail', false, 'This request cannot yet be handled via text - go to RVA311.com or call 3-1-1 to submit your request.'),
('Report Community Garden Issue', false, 'This request cannot yet be handled via text - go to RVA311.com or call 3-1-1 to submit your request.'),
('Report Litter On Public Property', false, 'This request cannot yet be handled via text - go to RVA311.com or call 3-1-1 to submit your request.'),
('Report Graffiti', false, 'This request cannot yet be handled via text - go to RVA311.com or call 3-1-1 to submit your request.'),
('Report Graffiti on Public Property', false, 'This request cannot yet be handled via text - go to RVA311.com or call 3-1-1 to submit your request.'),
('Report Graffiti on Private Property', false, 'This request cannot yet be handled via text - go to RVA311.com or call 3-1-1 to submit your request.'),
('Report Illegal Dumping', false, 'This request cannot yet be handled via text - go to RVA311.com or call 3-1-1 to submit your request.'),
('Assess Standing Water', false, 'This request cannot yet be handled via text - go to RVA311.com or call 3-1-1 to submit your request.'),
('Clean Stormwater Drain', false, 'This request cannot yet be handled via text - go to RVA311.com or call 3-1-1 to submit your request.'),
('Repair Stormwater Drain', false, 'This request cannot yet be handled via text - go to RVA311.com or call 3-1-1 to submit your request.'),
('Report Illicit Discharge To Stormwater', false, 'This request cannot yet be handled via text - go to RVA311.com or call 3-1-1 to submit your request.'),
('Missing Stormwater Manhole Cover', false, 'This request cannot yet be handled via text - go to RVA311.com or call 3-1-1 to submit your request.'),
('Report Missing Sewer Manhole Cover', false, 'This request cannot yet be handled via text - go to RVA311.com or call 3-1-1 to submit your request.'),
('Report Backup Of Sewer', false, 'This request cannot yet be handled via text - go to RVA311.com or call 3-1-1 to submit your request.'),
('Request Tv Of Sewer', false, 'This request cannot yet be handled via text - go to RVA311.com or call 3-1-1 to submit your request.'),
('Report Overflow Of Sewer', false, 'This request cannot yet be handled via text - go to RVA311.com or call 3-1-1 to submit your request.'),
('Report Odor From Sewer', false, 'This request cannot yet be handled via text - go to RVA311.com or call 3-1-1 to submit your request.'),
('Request Location Sewer Manhole', false, 'This request cannot yet be handled via text - go to RVA311.com or call 3-1-1 to submit your request.'),
('Report Sewer Manhole Problem', false, 'This request cannot yet be handled via text - go to RVA311.com or call 3-1-1 to submit your request.'),
('Request Location Sewer Lateral', false, 'This request cannot yet be handled via text - go to RVA311.com or call 3-1-1 to submit your request.'),
('Request Install Sewer Cleanout', false, 'This request cannot yet be handled via text - go to RVA311.com or call 3-1-1 to submit your request.'),
('Report Broken Sewer Cleanout', false, 'This request cannot yet be handled via text - go to RVA311.com or call 3-1-1 to submit your request.'),
('Admissions Transient Occupancy And Meals', false, 'This request cannot yet be handled via text - go to RVA311.com or call 3-1-1 to submit your request.'),
('Business Personal Property And Manufacturing & Tools', false, 'This request cannot yet be handled via text - go to RVA311.com or call 3-1-1 to submit your request.'),
('Business Professional And Occupational Licenses', false, 'This request cannot yet be handled via text - go to RVA311.com or call 3-1-1 to submit your request.'),
('Real Estate Taxes', false, 'This request cannot yet be handled via text - go to RVA311.com or call 3-1-1 to submit your request.'),
('Rva Stay - Gap Grant Program - Suspended', false, 'This request cannot yet be handled via text - go to RVA311.com or call 3-1-1 to submit your request.'),
('Real Estate Tax Relief For Older Adults Or Persons With Disabilities', false, 'This request cannot yet be handled via text - go to RVA311.com or call 3-1-1 to submit your request.'),
('Delinquent Collections', false, 'This request cannot yet be handled via text - go to RVA311.com or call 3-1-1 to submit your request.'),
('Report Private Property Maintenance Issues', false, 'This request cannot yet be handled via text - go to RVA311.com or call 3-1-1 to submit your request.'),
('Report Zoning, Building Occupancy Or Use', false, 'This request cannot yet be handled via text - go to RVA311.com or call 3-1-1 to submit your request.'),
('Report Unlawful Accumulation Of Debris/Items', false, 'This request cannot yet be handled via text - go to RVA311.com or call 3-1-1 to submit your request.'),
('Report Illegal Or Excessive Signage On Private Property', false, 'This request cannot yet be handled via text - go to RVA311.com or call 3-1-1 to submit your request.'),
('Report Building/Structural Condition', false, 'This request cannot yet be handled via text - go to RVA311.com or call 3-1-1 to submit your request.'),
('Report Public Right Of Way Concern', false, 'This request cannot yet be handled via text - go to RVA311.com or call 3-1-1 to submit your request.'),
('Report Private Property Construction Without A Permit', false, 'This request cannot yet be handled via text - go to RVA311.com or call 3-1-1 to submit your request.'),
('Parking Citation Concerns', false, 'This request cannot yet be handled via text - go to RVA311.com or call 3-1-1 to submit your request.'),
('Request Residential Parking Permit', false, 'This request cannot yet be handled via text - go to RVA311.com or call 3-1-1 to submit your request.'),
('Report Abandoned Vehicles On Private Property', false, 'This request cannot yet be handled via text - go to RVA311.com or call 3-1-1 to submit your request.'),
('Abandoned Vehicles on City Street', false, 'This request cannot yet be handled via text - go to RVA311.com or call 3-1-1 to submit your request.'),
('Request Graffiti Investigation', false, 'This request cannot yet be handled via text - go to RVA311.com or call 3-1-1 to submit your request.'),
('Report Speed Violations In Community', false, 'This request cannot yet be handled via text - go to RVA311.com or call 3-1-1 to submit your request.'),
('Report Clearing Or Erosion Issues On Construction Site', false, 'This request cannot yet be handled via text - go to RVA311.com or call 3-1-1 to submit your request.'),
('Report Infestation On Private Property', false, 'This request cannot yet be handled via text - go to RVA311.com or call 3-1-1 to submit your request.'),
('Report Vermin From Sewer', false, 'This request cannot yet be handled via text - go to RVA311.com or call 3-1-1 to submit your request.'),
('Seeking Worker Support', false, 'This request cannot yet be handled via text - go to RVA311.com or call 3-1-1 to submit your request.'),
('Request Aging And Disability Care And Support', false, 'This request cannot yet be handled via text - go to RVA311.com or call 3-1-1 to submit your request.'),
('Richmond Parks General (Non-Trail) Concerns', false, 'For non-trail (general) parks concerns, reach out to the Richmond Parks team at at askparkrec@rva.gov.'),
('Request Residential Trash Can', false, 'In order to request and pay for a residential trash can, go to RVA311.com or call 311.'),
('Request Business Trash Can Or Service Change', false, 'In order to request and pay for business trash can or service change, go to RVA311.com or call 311.'),
('Request Paid Bulk Or Appliance Pick Up', false, 'In order to request and pay for bulk or appliance pickup service by the Department of Public Works, go to RVA311.com or call 311.'),
('Paid Leaf Vacuum Service', false, 'In order to request and pay for leaf vacuum service by the Department of Public Works, go to RVA311.com or call 311.'),
('Rvapay Account Registration Support', false, 'Due to the personal nature of this request & the associated security concerns, go online to rva311.com to submit a RVAPay login difficulty request.'),
('Vehicle Personal Property Taxes', false, 'Requests related to Vehicle Personal Property taxes should be submitted through the Department of Finance''s new RVA Pay system. Please use the RVAPay link to access the new system and register for an account. In RVAPay you will be able to see all outstanding bills, view all of your past bills and make payments: rvapay.rva.gov'),
('How To Report Mosquitoes On Public Property', false, 'Mosquito concerns are assessed and addressed by different departments within the city depending on their origin. Go to RVA311.com to find links to the appropriate forms.'),
('Family Crisis Fund - Water Recovery - Paused', false, 'This program is currently paused. Find more information online at RVA311.com.'),
('How To Request Police Attendance At Community Event', false, 'To request police presence at an event, Contact the Sector Lieutenant for the Sector where the event will be held to arrange scheduling. To verify the correct sector and appropriate contact information, visit the Richmond Police Patrol Services page: https://www.rva.gov/police/patrol-services'),
('Shade Existing Streetlight - Discontinued', false, 'The streetlight shading program has been discontinued. Find more information online at RVA311.com.'),
('How To Get Free Bulk Trash Pick Up', false, 'The Department of Public Works'' Bulk Items crew will attempt to pick up your bulk items every other week on the same week as your recycling. No call or special scheduling required.');
